services:
  # Backend API service
  - type: web
    name: sign-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
    
  # Frontend web service
  - type: web
    name: sign-detection-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: PORT
        value: 3000
      - key: REACT_APP_API_URL
        value: https://sign-detection-api.onrender.com 